<?php

$options = [
    "Pesquise por “filhote de” + seu animal favorito no Google Imagens",
    "Recomende uma música",
    "Tente tocar o seu nariz com a língua",
    "Dance, sozinho, a sua música favorita",
    "Assista um episodio do seu desenho ou serie favorito da sua infância",
    "Recomende uma série para alguém",
    "Faça uma pizza caseira",
    "Passe um dia sem comer carne",
    "Imite a posição da arvore mais próxima a você",
    "Levante da onde você está e dê 5 pulos, volte ao que estava fazendo",
    "Conheça e baixe um novo app",
    "Publique o produto que você mais gosta e elogie",
    "Mude o idioma do seu celular por 24 horas",
    "Deite no chão e cante uma música",
    "Zere um jogo",
    "Liste 3 coisas que deixam você feliz",
    "Acesse o playback.fm e escute a música mais tocada no dia do seu nascimento",
    "Faça um barquinho de papel",
    "Faça um avião de papel",
    "Faça um ganso de papel",
    "Faça um chapéu de papel",
    "Liste 3 pessoas que te inspiram",
    "Recomende um filme para alguém",
    "Se você pediu comida por delivery, pergunte como está sendo o dia do entregador",
    "Coloque seu colchão na sala e durma lá hoje",
    "Pergunte para o seu mais novo amigo, qual o dia do aniversário dele e anote",
    "Dê uma segunda chance a uma série",
    "Dê uma segunda chance a um livro",
    "De uma segunda chance a um filme",
    "Pesquise qual o filme de mais sucesso no ano do seu nascimento e assista hoje",
    "Publique como indicação o filme que mudou sua vida",
    "Com leite em pó puro",
    "Liste 3 metas para fazer urgentemente depois da quarentena",
    "Pesquise seu nome no Google",
    "Pesquise a origem do seu nome",
    "Pesquise a origem da sua comida favorita",
    "Faça 3 agachamentos e volte ao que estava fazendo",
    "Cante uma música na frente do ventilador como se não houvesse o amanhã",
    "Conheça a história da sua cidade",
    "Conheça a história do nome da sua rua",
    "Abra o youtube e assista o 3° vídeo recomendado",
    "Leia um livro inteiro",
    "Conheça o Hino nacional de outro país",
    "Arrume seu guarda roupa",
    "Olhe para o céu por alguns minutos e respire fundo",
    "Olhe seu álbum de fotos antigos perto de alguém amado",
    "Faça uma lista de todas as pontas soltas que estão te tirando do sério",
    "Faça um presente e deixe na porta de um vizinho querido",
    "Faça uma carta e coloque por baixo da porta  de alguém especial",
    "Ligue por vídeo chamada para um idoso(próximo a você ou que seja seu vizinho)",
    "Conheça um amigo de um amigo",
    "Faça uma vídeo chamada com 20 pessoas (amigos e amigos dos amigos)",
    "Assista 5 filmes hoje com direito a pipoca",
    "Convide uma pessoa para assistir um filme através do RAVE(app) com você",
    "Vai pedir comida? Peça algo que você nunca comeu",
    "Escreva uma carta para o você do futuro no site futureme.org",
    "Crie seu próprio wallpaper",
    "Delete todos os arquivos do seu computador que não tem sido usado nos últimos 6 meses",
    "Delete as fotos do seu ex",
    "Compartilhe o quarenteners no twitter",
    "Fique um dia sem pular nenhuma musica da sua playlist",
    "Beba 5 copos de água seguidos",
    "Envie um cartão postal digital para alguém que mora longe",
    "Leia um artigo aleatório do wikipedia",
    "Crie uma playlist para os seus amigos",
    "Ligue para um vizinho(a) e pergunte como está o dia dele(a)",
    "Faça carinho no seu pet",
    "Não minta por 24 horas",
    "Planeje um passeio com seus amigos para depois da quarentena",
    "Diga “eu te amo” para alguém hoje",
    "Toque bateria ou guitarra invisível agora",
    "Faça um poema para a sua comida favorita",
    "Faça uma limpeza nos arquivos do seu celular",
    "Maratone uma série",
    "Assista um filme clássico que você nunca viu",
    "Faça yoga agora",
    "Dance com alguem no meio da sala",
    "Passe 24 horas sem fazer algo que você considera uma vício",
    "Publique uma foto da coisa mais velha que você tem no seu quarto",
    "Tome um banho de chuva no seu quintal",
    "Olhe-se no espelho e observe seus detalhes. Se ame",
    "Tire uma selfie e não publique",
    "Assista uma palestra do TED",
    "Aprenda uma piada nova e conte para alguém",
    "Aprenda uma piada nova e publique",
    "Escreva uma história",
    "Diga ou faça algo gentil para alguém que você não gosta",
    "Ofereça uma massagem para alguém do seu lado",
    "Crie um alfabeto",
    "Faça o próximo desafio com a pessoa do seu lado",
    "Faça uma massagem no seu próprio pé",
    "Elogie a próxima pessoa que aparecer",
    "Faça uma receita nova",
    "Faça bolo de caneca",
    "Conheça um autor brasileiro",
    "Assista um filme nacional",
    "Faça um bolo",
    "Alongue-se",
    "Assista Marley e eu , e tente não chorar",
    "Separe roupas que você não usa para doação",
    "Zere a caixa de entrada do seu e-mail",
    "Faça um ato de bondade e não diga nada sobre isso",
    "Use meias diferentes",
    "Tome banho descalço",
    "Coloque água e comida para um animal de rua",
    "Tente comer macarrão instantâneo de colher",
    "Tome banho com a luz apagada",
    "Veja o sol nascer",
    "Coma ou experimente açaí",
    "Faça algo que nunca fez, mas sempre quis",
    "Ouça o mar sem sair de casa",
    "Passe um dia sem reclamar",
    "Tome sorvete",
    "Escute sua música favorita em outro idioma",
    "Ande com uma toalha no ombro por 4 horas",
    "Faça um piquenique na sua sala com as pessoas que moram com você",
    "Ligue para um amigo de madrugada, diga “eu sou o batman” e desligue",
    "Dê unfollow em 5 amigos no twitter/instagram e dê follow novamente",
    "Conheça uma palavra estranha hoje",
    "Adote um amigo imaginário hoje e apresente ele para duas pessoas",
    "Converse só por emojis com a próxima pessoa",
    "Faça o desafio do papel higiênico agora",
    "Use uma roupa que você comprou e nunca usou,agora",
    "Publique uma foto antiga sua",
    "Recrie uma foto antiga sua",
    "Invente uma coreografia para a música mais tocada hoje",
    "Assista um filme de terror",
    "Assista um filme romântico",
    "Assista um filme dublado com outro idioma",
    "Elogie 5 pessoas que segue você no twitter/instagram",
    "Doe dois livros da sua estante",
    "Faça brigadeiro",
    "Assista o piloto de uma série nova",
    "Visite o lugar que você sonha em conhecer através do Google Earth",
    "Vista 15 camisas",
    "Tente dar uma estrelhinha",
    "Tente equilibrar uma colher no nariz",
    "Pinte suas unhas com uma cor que não goste",
    "Abra sua câmera agora e registre o que ela viu",
    "Poste suas 3 melhores fotos",
    "Tente tocar seu pé sem dobrar o joelho",
    "Deixe alguém maquiar você de olhos fechados e depois registre isso",
    "Dance ula-ula com alguém",
    "Dance Macarena",
    "Mexa no celular por 2 horas com a mão que você não domina",
    "Dance uma musica que marcou sua infância",
    "Recrie a abertura do seu desenho favorito da infância",
    "Recrie a melhor foto do seu artista favorito(a)",
    "Poste o que esta fazendo agora",
    "Diga  trecho de uma música que você cantava errado",
    "Assista High School Musical",
    "Dance pela casa inteira",
    "Faça um spa day",
    "Use apenas roupas amarelas",
    "Aprenda uma coreografia do Fitdance",
    "Poste uma lembrança engraçada da sua infância",
    "Poste a 4° foto da sua galeria",
    "Fale a coisa mais engraçada que aconteceu hoje",
    "Faça um cospobre",
    "Duble uma música",
    "Jogue UNO online com seus amigos",
    "Faça um pudim e divida-o"
];
