<?php

$options = [
    "Pesquise por “filhote de” + seu animal favorito no google imagens",
    "Recomende uma musica",
    "Tente tocar o seu nariz com a língua",
    "Dance, sozinho, a sua musica favorita",
    "Assista um episodio do seu desenho ou serie favorito da sua infância",
    "Recomende uma serie para alguém",
    "Faca uma pizza caseira",
    "Passe um dia sem comer carne",
    "Imite a posição da arvore mais próxima a você",
    "Levante da onde você esta e de 5 pulos, volte ao que estava fazendo",
    "Conheca e baixe um novo app",
    "Publique o produto que você mais gosta e elogie",
    "Mude o idioma do seu celular por 24 horas",
    "Deite no chão e cante uma musica",
    "Zere um jogo",
    "Liste 3 coisas que deixam você feliz",
    "Acesse o playback.fm e escute a musica mais tocada no dia do seu nascimento",
    "Faca um barquinho de papel",
    "Faca um avião de papel",
    "Faca um ganso de papel",
    "Faca um chapéu de papel",
    "Liste 3 pessoas que te inspiram",
    "Recomende um filme para alguém",
    "Se você pediu comida por delivery, pergunte como esta sendo o dia do entregador",
    "Coloque seu colchão na sala e durma la hoje",
    "Pergunte para o seu mais novo amigo, qual o dia do aniversario dele e anote",
    "De uma segunda chance a uma serie",
    "De uma segunda chance a um livro",
    "De uma segunda chance a um filme",
    "Pesquise qual o filme de mais sucesso no ano do seu nascimento e assista hoje",
    "Publique como indicação o filme que mudou sua vida",
    "Com leite em po puro",
    "Liste 3 metas para fazer urgentemente depois da quarentena",
    "Pesquise seu nome no google",
    "Pesquise a origem do seu nome",
    "Pesquise a origem da sua comida favorita",
    "Faca 3 agachamentos e volte ao que estava fazendo",
    "Cante uma musica na frente do ventilador como se não houvesse o amanha",
    "Conheca a historia da sua cidade",
    "Conheca a historia do nome da sua rua",
    "Abra o youtube e assista o 3° vídeo recomendado",
    "Leia um livro inteiro",
    "Conheca o hino nacional de outro pais",
    "Arrume seu guarda roupa",
    "Olhe para o ceu por alguns minutos e respire fundo",
    "Olhe seu álbum de fotos antigos perto de alguem amado",
    "Faca uma lista de todas as pontas soltas que estão te tirando do serio",
    "Faca um presente e deixe na porta de um vizinho querido",
    "Faca uma carta e coloque por baixo da porta  de alguem especial",
    "Ligue por vídeo chamada para um idoso(a) próximo a você ou vizinho",
    "Conheca um amigo de um amigo",
    "Faca uma vídeo chamada com 20 pessoas (amigos e amigos dos amigos)",
    "Assista 5 filmes hoje com direito a pipoca",
    "Convide uma pessoa para assistir um filme através do rave(app) com você",
    "Vai pedir comida? Peca algo que você nunca comeu",
    "Escreva uma carta para o você do futuro no site futureme.org",
    "Crie seu próprio wallpaper",
    "Delete todos os arquivos do seu computador que não tem sido usados nos últimos 6 meses",
    "Delete as fotos do seu ex",
    "Compartilhe o quarenteners no twitter",
    "Fique um dia sem pular nenhuma musica da sua plylist",
    "Beba 5 copos de agua seguidos",
    "Envie um cartão postal digital para alguem que mora longe",
    "Leia um artigo aleatório do wikipedia",
    "Crie uma playlist para os seus amigos",
    "Ligue para um vizinho(a) e pergunte como esta o dia dele(a)",
    "Faca carinho no seu pet",
    "Nao minta por 24 horas",
    "Planeje um passeio com seus amigos para depois da quarentena",
    "Diga “eu te amo” para alguem hoje",
    "Toque bateria ou guitarra invisível agora e não fale porquê",
    "Faca um poema para a sua comida favorita",
    "Faca uma limpeza nos arquivos do seu celular",
    "Maratone uma serie",
    "Assista um filme clássico que você nunca viu",
    "Faça yoga agora",
    "Dance com alguem no meio da sala",
    "Passe 24 horas sem fazer algo que você considera uma vicio",
    "Publique uma foto da coisa mais velha que você tem no seu quarto",
    "Tome um banho de chuva no seu quintal",
    "Olhe-se no espelho e observe seus detalhes. Se ame",
    "Tire uma selfie e não publique",
    "Assista uma palestra do TED",
    "Aprenda uma piada nova e conte para alguem",
    "Aprenda uma piada nova e publique",
    "Escreva uma historia",
    "Diga ou faça algo gentil para alguem que você não gosta",
    "Ofereça uma massagem para alguem do seu lado",
    "Crie um alfabeto",
    "Faca o próximo desafio com a pessoa do seu lado",
    "Faca uma massagem no seu próprio pe",
    "Elogie a próxima pessoa que aparecer",
    "Faca uma receita nova",
    "Faca bolo de caneca",
    "Conheca um autor brasileiro",
    "Assista um filme nacional",
    "Faca um bolo",
    "Alongue-se",
    "Assista Marley e eu , e tente não chorar",
    "Separe roupas que você não usa para doação",
    "Zere a caixa de entrada do seu email",
    "Faca um ato de bondade e não diga nada sobre isso",
    "Use meias diferentes",
    "Ande descalço",
    "Coloque agua e comida para um animal de rua",
    "Coma macarrão instantâneo de colher",
    "Tome banho com a luz apagada",
    "Veja o sol nascer",
    "Coma ou experimente açaí",
    "Faca algo que nunca fez, mas sempre quis",
    "Ouça o mar sem sair de casa",
    "Passe um dia sem reclamar",
    "Tome sorvete",
    "Escute sua musica favorita em outro idioma",
    "Ande com uma toalha no ombro por 4 horas",
    "Faca um piquenique na sua sala com as pessoas que moram com você",
    "Ligue para um amigo de madrugada, diga “eu sou o batman” e desligue",
    "De unfollow em 5 amigos no twitter/instagram e dê follow novamente",
    "Conhece uma palavra estranha hoje",
    "Adote um amigo imaginário hoje, apresente ele para duas pessoas",
    "Converse so por emojis com a próxima pessoa",
    "Faca o desafio do papel higiênico agora",
    "Use uma roupa que você comprou e nunca usou,agora",
    "Publique uma foto antiga sua",
    "Recrie uma foto antiga sua",
    "Invente uma coreografia para a musica mais tocada hoje",
    "Assista um filme de terror",
    "Assista um filme romântico",
    "Assista um filme dublado com outro idioma",
    "Elogie 5 pessoas que segue você no twitter/instagram",
    "Doe dois livros da sua estante",
    "Faca brigadeiro",
    "Assista o piloto de uma serie nova",
    "Visite o lugar que você sonha em conhecer através do google Earth",
    "Vista 15 camisas",
    "Tente dar uma estrelhinha",
    "Tente equilibrar uma colher no nariz",
    "Pinte suas unhas com uma cor que não goste",
    "Abra sua câmera agora e registre o que ela viu",
    "Poste suas 3 melhores fotos",
    "Tente tocar seu pé sem dobrar o joelho",
    "Deixe alguem maquiar você de olhos fechados e depois registre isso",
    "Dance ula-ula com alguem",
    "Dance Macarena",
    "Mexa no celular por 2 horas com a mão que você não domina",
    "Dance uma musica que marcou sua infância",
    "Recrie a abertura do seu desenho favorito da infância",
    "Recrie a melhor foto do seu artista favorito(a)",
    "Poste o que esta fazendo agora",
    "Diga  trecho de uma musica que você cantava errado",
    "Assista High School Musical",
    "Dance pela casa inteira",
    "Faca um spa day",
    "Use apenas roupas amarelas",
    "Aprenda uma coreografia do fitdance",
    "Poste uma lembrança engraçada da sua infância",
    "Poste a 4 foto da sua galeria",
    "Fale a coisa mais engraçada que aconteceu hoje",
    "Faça um cospobre",
    "Duble uma musica",
    "Jogue uno online com seus amigos",
    "Faça um pudim e divida-o"
];
